/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personalassistant;

import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;

/**
 *
 * @author Shreyas
 */
public class Popup extends javax.swing.JDialog {

    public static final int snoozeTime = 10_000;
    
    public static final int longPause = 60_000 * 30;
    public static final int shortPause = 10_000;
    
    public String targetDate = "";
    public String targetTime = "";
    public String message = "";
    
    /**
     * Creates new form Popup
     */
    public Popup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //init();
    }
    
    public Popup() {
        initComponents();
        
    }
    
    public void init() {
        setAlwaysOnTop(true);
        setVisible(true);
        txtMsg.setText(message);
        Insets toolHeight = Toolkit.getDefaultToolkit().getScreenInsets(getGraphicsConfiguration());
        Dimension scrSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    for (int i=0;i<getHeight();i++) {
                        setLocation(scrSize.width - getWidth(), scrSize.height - toolHeight.bottom-i);
                        Thread.sleep(2);
                    }
                    
                }
                catch (Exception e ) {
                    
                }
            }
        }).start();
        
    }
    
    public void startTimer() {
        System.out.println(getDate());
        System.out.println(targetDate);
        Thread reminder = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    while (!getDate().equals(targetDate)) {
                        Thread.sleep(longPause);
                    }
                    while (!getTime().equals(targetTime)) {
                        Thread.sleep(shortPause);
                    }
                    System.out.println("init");
                    init();
                }
                catch (Exception e) {
                    
                }
            }
        });
        reminder.start();
    }
    
    public String getDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MMM-yyyy");
        String date = s.format(d);
        return date;
    }
    
    public String getTime() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
        String time = s.format(d);
        time=time.substring(0,time.lastIndexOf(":"));
        System.out.println(targetTime+" "+time);
        return time;
    }
    
    public void dismissPopup() {
        dispose();
        //System.exit(0);
    }

    public void snoozePopup() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    dispose();
                    Thread.sleep(snoozeTime);
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            //new Popup().setVisible(true);
                            
                            Popup window = new Popup();
                            window.targetDate=targetDate;
                            window.targetTime=targetTime;
                            window.message=message;
                            window.startTimer();
                        }
                    });
                }
                catch (Exception e) {
                }
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDismiss = new javax.swing.JButton();
        btnSnooze = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnDismiss.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnDismiss.setText("Dismiss");
        btnDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDismissActionPerformed(evt);
            }
        });

        btnSnooze.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btnSnooze.setText("Snooze");
        btnSnooze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSnoozeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Reminder");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reminder.png"))); // NOI18N

        txtMsg.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        txtMsg.setText("Reminder triggered");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDismiss, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSnooze, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtMsg))
                        .addGap(0, 153, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMsg)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDismiss, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSnooze, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDismissActionPerformed
        // TODO add your handling code here:
        dismissPopup();
    }//GEN-LAST:event_btnDismissActionPerformed

    private void btnSnoozeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSnoozeActionPerformed
        // TODO add your handling code here:
        snoozePopup();
    }//GEN-LAST:event_btnSnoozeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Popup dialog = new Popup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDismiss;
    private javax.swing.JButton btnSnooze;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtMsg;
    // End of variables declaration//GEN-END:variables
}
